### PR TITLE
Add test case for process and data keywords

### PR DESCRIPTION
**Pull request by kborowinski**
Add test case for process and data keywords

### CODE REVIEW

**Comment by omniomi** [comment]
@kborowinski can you just add these with #101?

**Comment by kborowinski** [comment]
@omniomi CI fails on it. Any clue why?

image

**Comment by omniomi** [comment]
@kborowinski because  Appveyor is running the tests against the code on github. Haven't merged 101 yet so it's not fixed here. If you push these changes in #101 it will pass.

**Comment by tylerl0706** [comment]
@omniomi beat me to it :P

**Comment by kborowinski** [comment]
@omniomi @TravisEz13 Thank you guys and sorry for the mess (I'm still in the learning process). I've pushed these changes on #101. We can close this one.

**Comment by omniomi** [comment]
Moved to PR #101.

**Pull request closed without merging**
