### PR TITLE
Embedded subexpressions

### LINKED ISSUE #132: subexpression marker ($ in '$(') is in scope 'punctuation.definition.variable'
### Environment

- Editor and Version: VS Code: 1.26.0
- Your primary theme: Dark+

### Issue Description

The subexpression marker(the $ in '$(') is currently scoped in 'punctuation.definition.variable'.  This causes no colorization in most schemes, such then cause colorization issues in double quoted text subexpressions.

### Expected Behavior

I might think that it should be in a 'keyword' scope.   To play around, I modified the VS Code powershell.tmLanguage.json file, in two places, to change the $ in '$(' to be scoped as 'keyword.other.subexpression.powershell'.

This seems to get the result with themes, causing it to colorize the same as the @ in '@(' or '@{' which also scope as a 'keyword'.

### PR DESCRIPTION
**Pull request by msftrncs**
Improve embedded substatements, fix #132.

- Rename `#interpolatedStringContent` to `#subexpression`.
- Remove include `#interpolation` from `#subexpression`.
- Change scopes in `#interpolation` to include `meta.embedded`,  `keyword.other` was
`punctuation.definition.variable`.
- Change scope in root pattern for `$( )`, `keyword.other` was
`punctuation.definition.variable`. (No tests are present for this)
- Remove redundant includes from `#subexpression` and `#interpolation`.
- Adjust test, of embedded substatements in double quoted strings.

Sample appearance
- VS Code (before):
image

- VS Code:
image

- ATOM:
image

### CODE REVIEW

**Comment by andschwa** [comment]
@msftrncs Is this PR superseded by #156, or should we merge it while trying to get that one in (since it appears to be a complete rewrite)?

**Comment by msftrncs** [comment]
This was meant to be separate of #156, so that it could be benefitted from sooner.  Its one of several PR's I made trying to bring in some trivial fixes quicker.  This goes along with #173 and #175

**Review by rjmholt — APPROVED** [review]

**Review by andschwa — APPROVED** [review]

**Comment by andschwa** [comment]
Thanks @msftrncs! After evaluating the state of the tests, CI, and these three PRs, we went ahead and merged. What's the worst that could happen? 😁

**Comment by andschwa** [comment]
I know it took a _couple years_ but @msftrncs I wanted to let you know that [GitHub Linguist just shipped](https://github.com/github/linguist/releases/tag/v7.14.0) which includes this and a few of your other fixes!

**Pull request merged**
