### PR TITLE
Using, Requires, Hidden, and Static

### LINKED ISSUE #20: Improper syntax highlighting for #requires statement
I have a PowerShell code file with two `#requires` statements. The code works properly, but the syntax highlighting is improper.

Specifically:
- The `-module` on the second `#requires` statement should be consistently colored. Right now, the dash is colored differently from the parameter name.
- The `ServerManager` argument should be colored consistently with parameter values, according to the current theme (this might be debatable)

image

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

### PR DESCRIPTION
**Pull request by omniomi**
This contains three fixes:

- `using module/namespace` declaration. 

using

```
using namespace System.Xml
^ - keyword.control.using.powershell
      ^ - keyword.other.powershell
                ^ - variable.parameter.powershell
```

- `hidden`/`static` modifiers within classes. (`storage.modifier.powershell`)

hidden-static

- `#requires` declaration 

I have fixed the issues with -Version in requires showing different highlighting after a period and added scopes to the various parts of the statement in line with `using`.

```
#Requires -Version 3.0
^ - comment.line.number-sign.powershell
 ^ - keyword.control.requires.powershell
          ^ - keyword.other.powershell
                  ^ - variable.parameter.powershell
```

Use of hashtables in `-Modules` still needs to be fixed but will require work on the scoping of hashtables first.

requires

(screenshot using a different theme from previous two.)

fixes #20

### CODE REVIEW

**Comment by tylerl0706** [comment]
What did these look like before? Sorry, not at a computer atm

**Comment by omniomi** [comment]
@tylerl0706,

using-before

I debated scoping `#requires` like ISE where it's just a flat comment but technically it's like `using` in practice... Thoughts?

**Comment by tylerl0706** [comment]
I love it. Merging this in :)

**Comment by kborowinski** [comment]
@omniomi The coloring of *#requires* is still broken when you specify multiple statements in one line e.g:

**Multiline:**
vscode_05

**Singleline:**
vscode_04

*BTW love your improvements so far! Great job!*

**Comment by omniomi** [comment]
@kborowinski is that allowed? https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-5.1 doesn't show that as an option which is what I followed.

**Comment by kborowinski** [comment]
Single-line style works for sure, so I guess that it is allowed. Is it best practice? I don't know. Maybe @tylerl0706 can provide answer here.

**Comment by tylerl0706** [comment]
I think if it's supported in the language, syntax highlighting should reflect it even if it's not a best practice.

I do see multiple statements often when requiring a particular module with a specific version. 

```
#Requires -Module Foo -Version 3
```

I should have asked for this test, sorry @omniomi!

Glad that it at least falls back to a full comment rather than something funky.

**Comment by omniomi** [comment]
@tylerl0706, @kborowinski fixed here: https://github.com/PowerShell/EditorSyntax/pull/85

**Comment by kborowinski** [comment]
@omniomi Thank you, and sorry for late reporting.

**Comment by kborowinski** [comment]
@omniomi Found another issue with *requries* keyword unfortunately. It breaks comment highlighting when *requires* word is used:

image

**Comment by tylerl0706** [comment]
Dont worry about AppVeyor for right now :)

**Comment by omniomi** [comment]
@tylerl0706, @kborowinski, I just pushed the appveyor config #91

**Comment by omniomi** [comment]
Note: the hashtable example above is actually invalid and is a problem with the docs. I submitted a fix: https://github.com/PowerShell/PowerShell-Docs/pull/2412

**Pull request merged**
